//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenShelf
{
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.book_copies = new HashSet<BookCopy>();
        }
    
        public decimal bookId { get; set; }
        public string Title { get; set; }
        public string Isbn { get; set; }
        public long NumberOfCopies { get; set; }
        public string Authors { get; set; }
    
        public virtual ICollection<BookCopy> book_copies { get; set; }
    }
}
