//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopy
    {
        public decimal CopyId { get; set; }
        public decimal BookId { get; set; }
        public Nullable<decimal> ThoughtWorkerId { get; set; }
        public System.DateTime DateOfBorrow { get; set; }
        public string AvailabilityStatus { get; set; }
    
        public virtual Book BookObj { get; set; }
        public virtual ThoughtWorker ThoughtWorker { get; set; }
    }
}
