//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowDetails
    {
        public decimal transaction_id { get; set; }
        public decimal Book { get; set; }
        public decimal ThoughtWorker { get; set; }
        public System.DateTime DateOfBorrow { get; set; }
    
        public virtual Book book { get; set; }
        public virtual ThoughtWorker thoughtworker { get; set; }
    }
}
