//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoughtWorker
    {
        public ThoughtWorker()
        {
            this.borrow_details = new HashSet<BorrowDetails>();
        }
    
        public decimal empId { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<BorrowDetails> borrow_details { get; set; }
    }
}
